services:
  postgres:
    image: postgres:17

    container_name: wrms-postgres

    environment:
      POSTGRES_DB: wrms
      POSTGRES_USER: shubh
      POSTGRES_PASSWORD: 1234

    ports:
      - "5433:5432"

    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: